---
service: es-ingest-takeon-data
provider:
  name: aws
  role: arn:aws:iam::014669633018:role/lambda_invoke_lambda
  vpc:
      securityGroupIds:
        - ${file(../json_outputs/security_groups_output.json):SecurityGroups.0.GroupId}
      subnetIds:
        - ${file(../json_outputs/subnets_output.json):Subnets.0.SubnetId}
        - ${file(../json_outputs/subnets_output.json):Subnets.1.SubnetId}
  runtime: python3.7
  region: eu-west-2
  package:
    individually: true

functions:
  deploy-wrangler:
    name: es-ingest-takeon-data-wrangler
    handler: ingest_takeon_data.lambda_handler
    package:
      include:
        - ingest_takeon_data.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_marshmallow:2
      - arn:aws:lambda:eu-west-2:014669633018:layer:dev-es-commonfunctions:12
    tags:
      app: results
    environment:
      takeon_bucket_name: takeon.validationdb.export.bucket
      results_bucket_name: results-tf-vpc-s3
      in_file_name: takeon-data-export-2019-09-23-13:23:38
      out_file_name: ingest-out.json
      function_name: es-ingest-takeon-data-method
      checkpoint: 0
      queue_url: https://sqs.eu-west-2.amazonaws.com/014669633018/BMI_Results.fifo
      sqs_messageid_name: ingest-takeon-data
      sns_topic_arn: arn:aws:sns:eu-west-2:014669633018:BMIResults

  deploy-method:
    name: es-ingest-takeon-data-method
    handler: ingest_takeon_data-method.lambda_handler
    package:
      include:
        - ingest_takeon_data-method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      period: 201809
