
service: es-ingest-takeon-data
provider:
  name: aws
  runtime: python3.7
  region: eu-west-2
  package:
    individually: true

functions:
  deploy-function:
    name: es-ingest-takeon-data
    handler: ingest_takeon_data.lambda_handler
    package:
      include:
        - ingest_takeon_data.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      bucket_name: takeon.validationdb.export.bucket
      file_name: takeon-data-export-2019-09-23-13:23:38
      period: 201809
      sqs_queue_url: https://sqs.eu-west-2.amazonaws.com/014669633018/BMI_Results.fifo
      sqs_messageid_name: ingest-takeon-data
      sns_topic_arn: arn:aws:sns:eu-west-2:014669633018:BMIResults
      question_codes: ['601', '602', '603', '604', '605', '606', '607']
      question_labels: {
        '601': 'Q601_asphalting_sand',
        '602': 'Q602_building_soft_sand',
        '603': 'Q603_concreting_sand',
        '604': 'Q604_bituminous_gravel',
        '605': 'Q605_concreting_gravel',
        '606': 'Q606_other_gravel',
        '607': 'Q607_constructional_fill'
      }