---
service: es-ingest-takeon-data
provider:
  name: aws
  deploymentBucket:
    name: com.serverless.${self:provider.region}.results.ons.deploys
  role: arn:aws:iam::${self:custom.accountId}:role/lambda_invoke_lambda
  vpc:
    securityGroupIds:
      - ${file(../json_outputs/security_groups_output.json):SecurityGroups.0.GroupId}
    subnetIds:
      - ${file(../json_outputs/subnets_output.json):Subnets.0.SubnetId}
      - ${file(../json_outputs/subnets_output.json):Subnets.1.SubnetId}
  runtime: python3.7
  region: eu-west-2
  package:
    individually: true
  memorySize: 512
  timeout: 10
  tracing:
    lambda: true

custom:
  accounts: ${ssm:/aws/reference/secretsmanager/results-aws-accounts~true}
  accountId: ${self:custom.accounts.account-id}

functions:
  deploy-wrangler:
    name: es-ingest-takeon-data-wrangler
    handler: ingest_takeon_data_wrangler.lambda_handler
    package:
      include:
        - ingest_takeon_data_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:latest
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-common-functions:latest
    tags:
      app: results
    environment:
      checkpoint: 0
      method_name: es-ingest-takeon-data-method
      results_bucket_name: results-s3-bucket
      sns_topic_arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      takeon_bucket_name: takeon.validationdb.export.bucket

  deploy-method:
    name: es-ingest-takeon-data-method
    handler: ingest_takeon_data_method.lambda_handler
    package:
      include:
        - ingest_takeon_data_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:latest
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-common-functions:latest
    tags:
      app: results
    environment:
      period: 201809
plugins:
  - serverless-latest-layer-version
